source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

group :development, :test do
  # gem "better_errors" add to only development
  gem "binding_of_caller"
  gem 'rspec-rails'
end

group :test do
  # shoulda-matchers provides Rspec with one-liners that test common Rails functionality. These tests would otherwise be much longer, more complex, and error-prone. Read the docs: https://github.com/thoughtbot/shoulda-matchers
  gem 'shoulda-matchers'
  # A library for setting up Ruby objects as test data. Read the docs: https://github.com/thoughtbot/factory_girl_rails
  gem 'factory_girl_rails'
  gem 'faker'
  # Capybara helps you test web applications by simulating how a real user would interact with your app. Read the docs: https://github.com/jnicklas/capybara
  gem 'capybara'

  # browser automation framework, read the docs: http://docs.seleniumhq.org/
  gem 'selenium-webdriver'

  # we will use this to clean our testing database after each run. Read the docs: https://github.com/bmabey/database_cleaner
  gem 'database_cleaner'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
